<a href="https://colab.research.google.com/github/harithavijay11/harithavijay11/blob/main/Copy_of_Course4_Review_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#List Data Structure

In [ ]:
# 1. Creating Lists
numbers = [10, 20, 30, 40, 50]               # List of integers
fruits = ["apple", "banana", "mango"]        # List of strings
mixed = [1, "hello", 3.14, True]             # Mixed data types
nested = [[1, 2], [3, 4], [5, 6]]            # Nested list (list of lists)

print("Numbers:", numbers)
print("Fruits:", fruits)
print("Mixed:", mixed)
print("Nested:", nested)
print("-------------------------------------------------")

# 2. Accessing Elements
print("First number:", numbers[0])           # Indexing (0-based)
print("Last fruit:", fruits[-1])             # Negative indexing
print("Second element in nested list:", nested[1][0])  # Accessing nested elements
print("-------------------------------------------------")

# 3. Slicing
L=[23,34,45,67,66,89]
print("First 3 numbers:", numbers[0:3])      # Slicing [start:end]
print("From index 2 to end:", numbers[2:])   # Omitting end means till last
print("Every 2nd number:", numbers[::2])     # Step slicing
print("-------------------------------------------------")

# 4. Mutability (Lists can be modified)
print("Before update:", fruits)
fruits[1] = "orange"                         # Updating element
print("After update:", fruits)
print("-------------------------------------------------")

# 5. Adding Elements
fruits.append("grape")                       # Append single item
print("After append:", fruits)

fruits.extend(["kiwi", "melon"])            # Extend (add multiple items)
print("After extend:", fruits)

fruits.insert(1, "strawberry")               # Insert at specific position
print("After insert:", fruits)
print("-------------------------------------------------")

# 6. Removing Elements
fruits.remove("orange")                      # Remove by value
print("After remove:", fruits)

popped_item = fruits.pop()                   # Pop last item
print("Popped item:", popped_item)
print("After pop:", fruits)

del fruits[0]                                # Delete by index
print("After del:", fruits)
print("-------------------------------------------------")

# 7. Checking length
print("Number of fruits:", len(fruits))

# 8. Looping through list
print("Looping through numbers:")
for num in numbers:
    print(num)
print("-------------------------------------------------")

# 9. Clearing the list
numbers.clear()
print("Numbers after clear:", numbers)

Numbers: [10, 20, 30, 40, 50]
Fruits: ['apple', 'banana', 'mango']
Mixed: [1, 'hello', 3.14, True]
Nested: [[1, 2], [3, 4], [5, 6]]
-------------------------------------------------
First number: 10
Last fruit: mango
Second element in nested list: 3
-------------------------------------------------
First 3 numbers: [10, 20, 30]
From index 2 to end: [30, 40, 50]
Every 2nd number: [10, 30, 50]
-------------------------------------------------
Before update: ['apple', 'banana', 'mango']
After update: ['apple', 'orange', 'mango']
-------------------------------------------------
After append: ['apple', 'orange', 'mango', 'grape']
After extend: ['apple', 'orange', 'mango', 'grape', 'kiwi', 'melon']
After insert: ['apple', 'strawberry', 'orange', 'mango', 'grape', 'kiwi', 'melon']
-------------------------------------------------
After remove: ['apple', 'strawberry', 'mango', 'grape', 'kiwi', 'melon']
Popped item: melon
After pop: ['apple', 'strawberry', 'mango', 'grape', 'kiwi']
After del: ['strawberry', 'mango', 'grape', 'kiwi']
-------------------------------------------------
Number of fruits: 4
Looping through numbers:
10
20
30
40
50
-------------------------------------------------
Numbers after clear: []

In [ ]:
# 3. Slicing
L=[23,34,45,67,66,89,889,56]
# # print("First 3 numbers:", L[:3])      # Slicing [start:end]
# # print("From index 2 to end:", L[2:])   # Omitting end means till last
# print("Every 2nd number:", L[::2])     # Step slicing
# print( L[3:8:2])
# print(L[::-1])
# print(L[-2:-7:-1])
print(L[-7:-2])

[34, 45, 67, 66, 89]

In [ ]:
L[0]=100
print(L)

[100, 34, 45, 67, 66, 89, 889, 56]

#tuple

A tuple is an ordered collection of elements, just like a list.

Defined using parentheses () instead of square brackets [].

Example: my_tuple = (1, 2, 3)

Immutable- Can not make any changes

In [ ]:
t=(23,45,67,88)
print(t)
t[0]=100
print(t)

(23, 45, 67, 88)

TypeError: 'tuple' object does not support item assignment

#What is a Dictionary?
A dictionary is a collection of key-value pairs.

Keys must be unique and immutable (e.g., strings, numbers, tuples).

Values can be of any type.

Defined using curly braces {}

In [ ]:
student = {
    "name": "Alice",
    "age": 20,
    "course": "Data Analytics"
}


print(student["name"])      # Alice
print(student.get("age"))   # 20


student["email"] = "alice@example.com"  # Add new key-value pair
student["age"] = 21                     # Update existing value
print(student)


student.pop("course")  # Remove a key by name
del student["email"]   # Delete a key
print(student)

Alice
20
{'name': 'Alice', 'age': 21, 'course': 'Data Analytics', 'email': 'alice@example.com'}
{'name': 'Alice', 'age': 21}

In [ ]:
print(student.keys())    # dict_keys(['name', 'age'])
print(student.values())  # dict_values(['Alice', 21])
print(student.items())   # dict_items([('name', 'Alice'), ('age', 21)])

dict_keys(['name', 'age'])
dict_values(['Alice', 21])
dict_items([('name', 'Alice'), ('age', 21)])

In [ ]:
employees = {}  # Empty dictionary
L=[]
# Adding data dynamically

for i in range(0,4):
  dept=input("Enter Dept:")
  employees[i]=dept


print(employees)

Enter Dept:r
Enter Dept:3
Enter Dept:4
Enter Dept:3
{0: 'r', 1: '3', 2: '4', 3: '3'}

#Numpy

What is NumPy?
NumPy (Numerical Python) is a Python library used for fast numerical computations.

It provides the ndarray (N-dimensional array) data structure.

It’s more efficient than lists for mathematical operations and is widely used in data analysis and machine learning.

Key Features
Fast performance: Vectorized operations (no loops needed).

Supports multi-dimensional arrays: 1D, 2D (matrix), 3D, etc.

Built-in mathematical functions: sum, mean, sqrt, etc.

Easy integration: Works with Pandas, Matplotlib, and other libraries.

In [ ]:
import numpy as np

# 1D array
arr1 = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr1)

# 2D array (matrix)
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2D Array:\n", arr2)

1D Array: [1 2 3 4 5]

2D Array:
 [[1 2 3]
 [4 5 6]]

A NumPy array is homogeneous—it stores elements of the same data type. While it is primarily used for numerical computations, it can also store strings, booleans, dates, or objects.
NumPy arrays are stored in contiguous memory.
Most operations are implemented in optimized C code, so they avoid the overhead of Python loops.
This makes NumPy significantly faster, especially for large datasets.

In [ ]:
import numpy as np

# Integers
a = np.array([1, 2, 3])

# Floats
b = np.array([1.5, 2.8, 3.2])

# Strings
c = np.array(["apple", "banana", "orange"])

# Booleans
d = np.array([True, False, True])

In [ ]:
L=[23,34,56,77]
L2=[23,45,56,67]
print(L+L2)

[23, 34, 56, 77, 23, 45, 56, 67]

In [ ]:
print("Shape:", arr2.shape)       # (2, 3)
print("Dimensions:", arr2.ndim)   # 2
print("Data Type:", arr2.dtype)   # int64

In [ ]:
# Element-wise operations
import numpy as np

# 1D array
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2D Array:\n", arr2)
print("1D Array:", arr1)
print("Add 10:", arr1 + 10)
print("Square:", arr1 ** 2)
print("Sum:", arr1.sum())
print("Mean:", arr1.mean())
print("First 3 elements:", arr1[0:3])       # Slicing
print("Element at row 1, col 2:", arr2[0, 1])  # Accessing 2D element
print("Zeros:\n", np.zeros((2, 3)))      # 2x3 array of zeros
print("Ones:\n", np.ones((2, 2)))        # 2x2 array of ones
print("Range:\n", np.arange(1, 10, 2))   # Array from 1 to 9 with step 2
print("Random:\n", np.random.rand(2, 2)) # 2x2 random array

2D Array:
 [[1 2 3]
 [4 5 6]]
1D Array: [1 2 3 4 5]
Add 10: [11 12 13 14 15]
Square: [ 1  4  9 16 25]
Sum: 15
Mean: 3.0
First 3 elements: [1 2 3]
Element at row 1, col 2: 2
Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1.]
 [1. 1.]]
Range:
 [1 3 5 7 9]
Random:
 [[0.79999811 0.7993448 ]
 [0.95759451 0.43201235]]

In [ ]:
#Create two numpy arrays with values between 20-30 and print sum of both the arrays
import numpy as np

arr1=np.arange(20,31)
print(arr1)
arr2=np.arange(20,31)
print(arr2)
print(arr1+arr2)

#What is Pandas?
Pandas is a Python library used for data analysis and manipulation.

It provides two main data structures:

Series – 1-dimensional labeled array.

DataFrame – 2-dimensional labeled table (like Excel).

**Pandas Series**

A Series is similar to a list or a single column in Excel but with labels (index).

Can store integers, floats, strings, or even mixed data.

Key Features
Has an index (row labels).

Can be created from a list, dictionary, or array.

Supports vectorized operations (fast calculations).

Example Use Cases:

Storing sales numbers for a week.

Keeping a list of product prices.

In [ ]:
import pandas as pd

# Creating a Series from a list
sales = [200, 300, 250, 400, 500]
# data=pd.Series(sales)
# print(data)

sales_series = pd.Series(sales, index=["Mon", "Tue", "Wed", "Thu", "Fri"])

print("Sales Series:")
print(sales_series)
print("\nAccessing a single value (Wed):", sales_series["Wed"])

Sales Series:
Mon    200
Tue    300
Wed    250
Thu    400
Fri    500
dtype: int64

Accessing a single value (Wed): 250

**Pandas DataFrame**

A DataFrame is like an Excel spreadsheet or SQL table.

Consists of rows and columns, where each column is a Series.

Key Features
Can be created from dictionaries, lists of dictionaries, or CSV/Excel files.

Has both row index and column labels.

Supports filtering, grouping, merging, and more.

Example Use Cases:

Storing employee data (Name, Department, Salary).

Analyzing large datasets (sales, customer records).

In [ ]:
import pandas as pd

# Creating a DataFrame from a dictionary
data = {
    "Employee": ["Alice", "Bob", "Charlie", "David"],
    "Department": ["HR", "IT", "Finance", "IT"],
    "Salary": [50000, 60000, 55000, 65000]
}



df = pd.DataFrame(data)
print(df)

df2 = pd.DataFrame(data,index=['Monday','Tuesday','Wednesday','Thursday'])

print(df2)
# print("\nEmployee DataFrame:")
# print(df)

# # Accessing columns
# print("\nSalaries column:")
# print(df["Salary"])


# #Access multiple columns

# print(df[['Name', 'City']])

# #Access a row by index

# df.loc[2]     # By label
# df.iloc[2]    # By position

# #Access a specific value

# df.at[1, 'Score']    # By label
# df.iat[1, 3]         # By position

  Employee Department  Salary
0    Alice         HR   50000
1      Bob         IT   60000
2  Charlie    Finance   55000
3    David         IT   65000
          Employee Department  Salary
Monday       Alice         HR   50000
Tuesday        Bob         IT   60000
Wednesday  Charlie    Finance   55000
Thursday     David         IT   65000

In [ ]:
import pandas as pd
data=pd.read_csv("Chicago_Crime_Data.csv")
# data.head(20)
data.tail(5)

,ID,CASE_NUMBER,DATE,BLOCK,IUCR,PRIMARY_TYPE,DESCRIPTION,LOCATION_DESCRIPTION,ARREST,DOMESTIC,...,WARD,COMMUNITY_AREA_NUMBER,FBICODE,X_COORDINATE,Y_COORDINATE,YEAR,UPDATEDON,LATITUDE,LONGITUDE,LOCATION
528,10453948,HZ192829,03/01/2016 12:00:00 AM,028XX E 79TH ST,1055,HUMAN TRAFFICKING,INVOLUNTARY SERVITUDE,APARTMENT,False,False,...,7.0,46.0,26,1196679.0,1853139.0,2016,02/10/2018 03:50:01 PM,41.751885,-87.554826,"(41.751885152, -87.554825997)"
529,10397129,HZ133234,01/29/2016 03:30:00 PM,006XX W HARRISON ST,5114,NON - CRIMINAL,FOID - REVOCATION,STREET,False,False,...,2.0,28.0,26,1172257.0,1897564.0,2016,02/10/2018 03:50:01 PM,41.874363,-87.643013,"(41.874363279, -87.643013039)"
530,3269495,HJ747227,11/08/2003 04:54:15 PM,012XX W 81ST ST,510,RITUALISM,AGG RIT MUT: HANDS/FIST/FEET SERIOUS INJURY,OTHER,False,False,...,21.0,71.0,04B,1169648.0,1851076.0,2003,02/28/2018 03:56:25 PM,41.746852,-87.653941,"(41.746852486, -87.653941385)"
531,10840565,JA143710,02/06/2017 01:20:00 PM,009XX N KARLOV AVE,5073,NON-CRIMINAL (SUBJECT SPECIFIED),NOTIFICATION OF CIVIL NO CONTACT ORDER,RESIDENCE,False,True,...,37.0,23.0,26,1148881.0,1905963.0,2017,02/14/2017 03:49:42 PM,41.897895,-87.728622,"(41.89789489, -87.728622316)"
532,1326195,G021609,01/11/2001 02:30:41 AM,087XX S ESCANABA AV,9901,DOMESTIC VIOLENCE,DOMESTIC VIOLENCE,APARTMENT,True,True,...,NaN,NaN,08B,1196869.0,1847416.0,2001,08/17/2015 03:03:40 PM,41.736176,-87.554320,"(41.73617608, -87.554319607)"

In [ ]:
data.iloc[450,1:5]

DATE            03/19/2017 10:35:00 AM
BLOCK             036XX W ROOSEVELT RD
IUCR                              031A
PRIMARY_TYPE                   ROBBERY
Name: JA192460, dtype: object

In [ ]:
data.loc[:,'DATE':'IUCR']

                               DATE                     BLOCK  IUCR
CASE_NUMBER
HK587712     08/28/2004 05:50:56 PM        047XX S KEDZIE AVE   890
HK456306     06/26/2004 12:40:00 PM  009XX N CENTRAL PARK AVE   820
HT233595     04/04/2011 05:45:00 AM        043XX S WABASH AVE   820
HT133522     12/30/2010 04:30:00 PM      083XX S KINGSTON AVE   840
HZ138551     02/02/2016 07:30:00 PM           033XX W 66TH ST   820
...                             ...                       ...   ...
HZ192829     03/01/2016 12:00:00 AM           028XX E 79TH ST  1055
HZ133234     01/29/2016 03:30:00 PM       006XX W HARRISON ST  5114
HJ747227     11/08/2003 04:54:15 PM           012XX W 81ST ST   510
JA143710     02/06/2017 01:20:00 PM        009XX N KARLOV AVE  5073
G021609      01/11/2001 02:30:41 AM       087XX S ESCANABA AV  9901

[533 rows x 3 columns]

In [ ]:
data['CASE_NUMBER'].head()

0    HK587712
1    HK456306
2    HT233595
3    HT133522
4    HZ138551
Name: CASE_NUMBER, dtype: object

In [ ]:
cond=data['CASE_NUMBER']=='HZ133234'
data[cond]

,ID,CASE_NUMBER,DATE,BLOCK,IUCR,PRIMARY_TYPE,DESCRIPTION,LOCATION_DESCRIPTION,ARREST,DOMESTIC,...,WARD,COMMUNITY_AREA_NUMBER,FBICODE,X_COORDINATE,Y_COORDINATE,YEAR,UPDATEDON,LATITUDE,LONGITUDE,LOCATION
529,10397129,HZ133234,01/29/2016 03:30:00 PM,006XX W HARRISON ST,5114,NON - CRIMINAL,FOID - REVOCATION,STREET,False,False,...,2.0,28.0,26,1172257.0,1897564.0,2016,02/10/2018 03:50:01 PM,41.874363,-87.643013,"(41.874363279, -87.643013039)"

In [ ]:
data.CASE_NUMBER.head()

0    HK587712
1    HK456306
2    HT233595
3    HT133522
4    HZ138551
Name: CASE_NUMBER, dtype: object

In [ ]:
data[data['DESCRIPTION']=='CYBERSTALKING']

,ID,CASE_NUMBER,DATE,BLOCK,IUCR,PRIMARY_TYPE,DESCRIPTION,LOCATION_DESCRIPTION,ARREST,DOMESTIC,...,WARD,COMMUNITY_AREA_NUMBER,FBICODE,X_COORDINATE,Y_COORDINATE,YEAR,UPDATEDON,LATITUDE,LONGITUDE,LOCATION
522,9094512,HW238778,04/15/2013 06:52:00 PM,038XX N SPAULDING AVE,583,STALKING,CYBERSTALKING,RESIDENCE,False,True,...,33.0,16.0,08A,1153706.0,1925344.0,2013,02/10/2018 03:50:01 PM,41.950983,-87.710383,"(41.950983256, -87.71038332)"

#Boolean Filtering in Pandas

In [ ]:

#Filter rows where Age > 30

# data[data['IUCR'] > 200]

#Filter where City is 'Toronto'

# df[df['City'] == 'Toronto']

# #Combine multiple conditions (AND)

# df[(df['Age'] > 25) & (df['Score'] > 85)]

# #OR condition

# df[(df['Age'] < 25) | (df['Score'] > 90)]

ValueError: invalid literal for int() with base 10: '041A'

In [ ]:
data.set_index('CASE_NUMBER', inplace=True)

In [ ]:
data.head()

,ID,DATE,BLOCK,IUCR,PRIMARY_TYPE,DESCRIPTION,LOCATION_DESCRIPTION,ARREST,DOMESTIC,BEAT,...,WARD,COMMUNITY_AREA_NUMBER,FBICODE,X_COORDINATE,Y_COORDINATE,YEAR,UPDATEDON,LATITUDE,LONGITUDE,LOCATION
CASE_NUMBER,,,,,,,,,,,,,,,,,,,,,
HK587712,3512276,08/28/2004 05:50:56 PM,047XX S KEDZIE AVE,890,THEFT,FROM BUILDING,SMALL RETAIL STORE,False,False,911,...,14.0,58.0,6,1155838.0,1873050.0,2004,02/10/2018 03:50:01 PM,41.807440,-87.703956,"(41.8074405, -87.703955849)"
HK456306,3406613,06/26/2004 12:40:00 PM,009XX N CENTRAL PARK AVE,820,THEFT,$500 AND UNDER,OTHER,False,False,1112,...,27.0,23.0,6,1152206.0,1906127.0,2004,02/28/2018 03:56:25 PM,41.898280,-87.716406,"(41.898279962, -87.716405505)"
HT233595,8002131,04/04/2011 05:45:00 AM,043XX S WABASH AVE,820,THEFT,$500 AND UNDER,NURSING HOME/RETIREMENT HOME,False,False,221,...,3.0,38.0,6,1177436.0,1876313.0,2011,02/10/2018 03:50:01 PM,41.815933,-87.624642,"(41.815933131, -87.624642127)"
HT133522,7903289,12/30/2010 04:30:00 PM,083XX S KINGSTON AVE,840,THEFT,FINANCIAL ID THEFT: OVER $300,RESIDENCE,False,False,423,...,7.0,46.0,6,1194622.0,1850125.0,2010,02/10/2018 03:50:01 PM,41.743665,-87.562463,"(41.743665322, -87.562462756)"
HZ138551,10402076,02/02/2016 07:30:00 PM,033XX W 66TH ST,820,THEFT,$500 AND UNDER,ALLEY,False,False,831,...,15.0,66.0,6,1155240.0,1860661.0,2016,02/10/2018 03:50:01 PM,41.773455,-87.706480,"(41.773455295, -87.706480471)"

In [ ]:
df.head()

  Employee Department  Salary
0    Alice         HR   50000
1      Bob         IT   60000
2  Charlie    Finance   55000
3    David         IT   65000

In [ ]:
df['Employee']

0      Alice
1        Bob
2    Charlie
3      David
Name: Employee, dtype: object

In [ ]:
#Slicing rows- iloc for index

df.iloc[1:4]         # Rows 1, 2, and 3
         # First 3 rows

  Employee Department  Salary
1      Bob         IT   60000
2  Charlie    Finance   55000
3    David         IT   65000

In [ ]:
df.iloc[:3]

  Employee Department  Salary
0    Alice         HR   50000
1      Bob         IT   60000
2  Charlie    Finance   55000

In [ ]:
df.head()

          Employee Department  Salary
Monday       Alice         HR   50000
Tuesday        Bob         IT   60000
Wednesday  Charlie    Finance   55000
Thursday     David         IT   65000

In [ ]:
df.loc['Monday']

Employee      Alice
Department       HR
Salary        50000
Name: Monday, dtype: object

In [ ]:
#Access specific row and column

df.iloc[0, 1]        # Row 0, Column 1 → Age of Alice
df.iloc[4, 3]        # Row 4, Column 3 → Score of Eva

In [ ]:
#Access multiple columns

df.iloc[:, [0, 2]]   # All rows, columns 0 and 2

In [ ]:
#Access last row

df.iloc[-1]

In [ ]:
#Access row and column by name

df.loc[0, 'Score']   # Score of Alice
df.loc[2, 'City']    # Charlie's city
#Access multiple columns

df.loc[:, ['Name', 'Score']]

#Index Filtering
Set column as index

df_indexed = df.set_index('Name')
Access using new index

df_indexed.loc['Bob']
Reset index

df_indexed.reset_index()

Removing Data
Remove a column

df.drop(columns=['City'])
Remove a row by index

df.drop(index=2)
Remove using condition

df[df['Age'] != 30]  # removes row where age = 30
✅ 5. Updating / Modifying Data
Update a specific value

df.at[0, 'Score'] = 95.0
Add a new column

df['Passed'] = df['Score'] > 80
✅ 6. Sorting and Ranking
Sort by Age

df.sort_values(by='Age')
Sort descending by Score

df.sort_values(by='Score', ascending=False)
✅ 7. Other Useful Operations
Summary statistics

df.describe()
Check data types

df.dtypes
Check for missing values

df.isnull().sum()
Filter using isin

df[df['City'].isin(['Toronto', 'Calgary'])]

| Function      | Purpose                              | Example                      | Output                     |
| ------------- | ------------------------------------ | ---------------------------- | -------------------------- |
| `max()`       | Find maximum value                   | `df["Salary"].max()`         | `105000`                   |
| `min()`       | Find minimum value                   | `df["Salary"].min()`         | `65000`                    |
| `idxmax()`    | Find index/location of maximum value | `df["Salary"].idxmax()`      | `5`                        |
| `idxmin()`    | Find index/location of minimum value | `df["Salary"].idxmin()`      | `3`                        |
| `nlargest()`  | Get top N largest values/rows        | `df.nlargest(3,"Salary")`    | Top 3 salaries             |
| `nsmallest()` | Get bottom N smallest values/rows    | `df.nsmallest(3,"Salary")`   | Lowest 3 salaries          |
| `mean()`      | Calculate average                    | `df["Salary"].mean()`        | Average salary             |
| `median()`    | Find middle value                    | `df["Salary"].median()`      | Middle salary              |
| `mode()`      | Find most frequent value             | `df["Department"].mode()`    | Most common department     |
| `sum()`       | Add all values                       | `df["Projects"].sum()`       | Total projects             |
| `count()`     | Count non-null values                | `df["Salary"].count()`       | Number of salaries         |
| `std()`       | Standard deviation                   | `df["Salary"].std()`         | Spread of data             |
| `var()`       | Variance                             | `df["Salary"].var()`         | Data variability           |
| `quantile()`  | Find percentile values               | `df["Salary"].quantile(0.5)` | Median                     |
| `describe()`  | Statistical summary                  | `df["Salary"].describe()`    | count, mean, min, max etc. |